### ISSUE TITLE
Which OS is used

### ISSUE THREAD

**Issue by carlos22** [rukzuk/circleci#1]
The used OS is not clear.
https://hub.docker.com/r/circleci/php/tags/
https://circleci.com/docs/2.0/circleci-images/#php

I assume it is debian, but which version? Always the latest stable?
Should be at least documented.

**Comment by trunneml** [comment]
The image is based on the latest [official php 5.6 image](https://hub.docker.com/_/php/), that is also taged as: 
- 5.6.38-cli-stretch
- 5.6-cli-stretch
- 5-cli-stretch
- 5.6.38-stretch
- 5.6-stretch
- 5-stretch
- 5.6.38-cli
- 5.6-cli
- 5-cli
- 5.6.38
- 5.6, 5 (5.6/stretch/cli/Dockerfile)

So currently it is based on debian stretch, but that can change in the future. The only thing that shouldn't change is the Php Version 5.6. ;-)

**Comment by carlos22** [comment]
Hm ok great, how did you know it is based on the official php image? I could not find that information!

Edit, ok the docs links has something like, but thats a bit vague:
> These images are typically extensions of official Docker images and include tools especially useful for CI/CD

**Comment by trunneml** [comment]
I looked into the source. ;-)

https://github.com/circleci/circleci-images/blob/staging/php/generate-images

**Comment by carlos22** [comment]
That is en excellent idea :-) The source is not linked in any of docs...
